the code is crashing like this (occasionally)
2020-03-14 07:16:15.108660801 UTC src/main.rs:14 get device
2020-03-14 07:16:15.168186443 UTC src/main.rs:25 allocate buffers
2020-03-14 07:16:15.168318210 UTC src/main.rs:32 launch
2020-03-14 07:16:15.168338859 UTC src/main.rs:39 sync
thread 'main' panicked at 'Failed to deallocate CUDA Device memory.: IllegalAddress', /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/rustacuda-0.1.2/src/memory/device/device_buffer.rs:259:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Failed to deallocate CUDA Device memory.: IllegalAddress', /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/rustacuda-0.1.2/src/memory/device/device_buffer.rs:259:17
stack backtrace:
   0:     0x55de6dc7a634 - backtrace::backtrace::libunwind::trace::hb7abe63e6a0c3513
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x55de6dc7a634 - backtrace::backtrace::trace_unsynchronized::h13230212e72260e1
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x55de6dc7a634 - std::sys_common::backtrace::_print_fmt::h9334643e8970688e
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55de6dc7a634 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6eca31551cbcbdc1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55de6dc9716c - core::fmt::write::h798629dd06ef5b45
                               at src/libcore/fmt/mod.rs:1063
   5:     0x55de6dc78ab3 - std::io::Write::write_fmt::hc3a26bb959047cc3
                               at src/libstd/io/mod.rs:1426
   6:     0x55de6dc7cb65 - std::sys_common::backtrace::_print::hb8c3996be6d5b09b
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55de6dc7cb65 - std::sys_common::backtrace::print::hfa893e74c57fbf51
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55de6dc7cb65 - std::panicking::default_hook::{{closure}}::h412b87b0488178e8
                               at src/libstd/panicking.rs:204
   9:     0x55de6dc7c8b2 - std::panicking::default_hook::hf08ab097a860ebdc
                               at src/libstd/panicking.rs:224
  10:     0x55de6dc7d122 - std::panicking::rust_panic_with_hook::h7383ba38703a6942
                               at src/libstd/panicking.rs:470
  11:     0x55de6dc7cd0b - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x55de6dc95b71 - core::panicking::panic_fmt::h988abaacf92f5d48
                               at src/libcore/panicking.rs:111
  13:     0x55de6dc95993 - core::option::expect_none_failed::h55ac55bf1bacf7e1
                               at src/libcore/option.rs:1211
  14:     0x55de6dc71b4e - core::result::Result<T,E>::expect::h59a002fb9c31a58d
                               at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libcore/result.rs:961
  15:     0x55de6dc67480 - <rustacuda::memory::device::device_buffer::DeviceBuffer<T> as core::ops::drop::Drop>::drop::h4c686775f2779cf7
                               at /home/martin/.cargo/registry/src/github.com-1ecc6299db9ec823/rustacuda-0.1.2/src/memory/device/device_buffer.rs:259
  16:     0x55de6dc6763a - core::ptr::drop_in_place::h7631338cb53afaa2
                               at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libcore/ptr/mod.rs:177
  17:     0x55de6dc6557b - code::main::h22d0b3ebea91c5b3
                               at src/main.rs:51
  18:     0x55de6dc6380b - std::rt::lang_start::{{closure}}::hed45e7b0a84b48e1
                               at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/rt.rs:67
  19:     0x55de6dc7cc33 - std::rt::lang_start_internal::{{closure}}::he9ff51989ddfd95d
                               at src/libstd/rt.rs:52
  20:     0x55de6dc7cc33 - std::panicking::try::do_call::h0a8df35330247eb9
                               at src/libstd/panicking.rs:303
  21:     0x55de6dc7e427 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  22:     0x55de6dc7d63c - std::panicking::try::h65198d931da604eb
                               at src/libstd/panicking.rs:281
  23:     0x55de6dc7d63c - std::panic::catch_unwind::h6b0e49979be8a7f3
                               at src/libstd/panic.rs:394
  24:     0x55de6dc7d63c - std::rt::lang_start_internal::h18ec8d99f8c24364
                               at src/libstd/rt.rs:51
  25:     0x55de6dc637e7 - std::rt::lang_start::h9ad802cd0960caab
                               at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/rt.rs:67
  26:     0x55de6dc6673a - main
  27:     0x7f3b41225e9b - __libc_start_main
  28:     0x55de6dc6318a - _start
  29:                0x0 - <unknown>