canvas was missing
now:

Error importing `index.js`: ERROR: 0:2: 'gl_FragColor' : undeclared identifier
ERROR: 0:2: 'assign' : l-value required (can't modify a const)
ERROR: 0:2: '=' : dimension mismatch
ERROR: 0:2: 'assign' : cannot convert from 'const 4-component vector of float' to 'const highp float'
bootstrap.js:5:23